name: newflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 👇 Add your image assets here
  assets:


    - images/coffee.png
    - images/login_bg.png
    - images/cappuccino.jpeg
    - images/black.jpeg
    - images/velila.jpeg
    - images/choocliatecofee.jpeg
    - images/cold.jpeg
    - images/icedcappuccino.jpg
    - images/strawberry.jpeg
    - images/palkova.jpg
    - images/blueberry.png
    - images/blacforest.jpeg
    - images/chocliatecake.jpeg
    - images/whiteforest.jpeg



     # login page background
